### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by tbekolay** [ctn-waterloo/best-practices#1]
GPL works for me, but it does limit things if, for example, ABR builds on this stuff. Might behoove us to use something more liberal like MIT just in case.

**Comment by celiasmith** [comment]
+1 MIT

Trevor Bekolay wrote:

**Comment by tcstewar** [comment]
Changed!   

(Although my understanding is that we don't really have to worry too much about GPL limitations if all the contributors are part of ABR, as we could just dual-license, but yeah, it's probably easier to just MIT)
